config/routes.rb
BrewHaHaRuby::Application.routes.draw do
  resources :contestants

end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
  attr_accessible :date_added, :description, :first_name, :id, :last_name, :nickname, :avatar
  has_attached_file :avatar, :styles => {:medium => "300x300>", :thumb => "100x100>" }
  self.primary_key = "id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  # GET /contestants
  # GET /contestants.json
  def index
    @contestants = Contestant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contestants }
    end
  end

  # GET /contestants/1
  # GET /contestants/1.json
  def show
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/new
  # GET /contestants/new.json
  def new
    @contestant = Contestant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contestant }
    end
  end

  # GET /contestants/1/edit
  def edit
    @contestant = Contestant.find(params[:id])
  end

  # POST /contestants
  # POST /contestants.json
  def create
    @contestant = Contestant.new(params[:contestant])

    respond_to do |format|
      if @contestant.save
        format.html { redirect_to @contestant, notice: 'Contestant was successfully created.' }
        format.json { render json: @contestant, status: :created, location: @contestant }
      else
        format.html { render action: "new" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contestants/1
  # PUT /contestants/1.json
  def update
    @contestant = Contestant.find(params[:id])

    respond_to do |format|
      if @contestant.update_attributes(params[:contestant])
        format.html { redirect_to @contestant, notice: 'Contestant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contestants/1
  # DELETE /contestants/1.json
  def destroy
    @contestant = Contestant.find(params[:id])
    @contestant.destroy

    respond_to do |format|
      format.html { redirect_to contestants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/views/contestants/_form.html.haml
= form_for @contestant, :html => { :multipart => true } do |f|
  - if @contestant.errors.any?
    %div{id:"error_explanation"}

      %h2 "#{pluralize(@contestant.errors.count, "error")} prohibited this contestant from being saved:"

      %ul
      - @contestant.errors.full_messages.each do |msg|
        %li= msg

  %div{class:"field"}
    = f.label :last_name
    %br
    = f.text_field :last_name

  %div{class:"field"}
    = f.label :first_name
    %br
    = f.text_field :first_name

  = image_tag @contestant.avatar.url, :class => "profile-image-small"

  %div{class:"field"}
    = f.label :avatar
    %br
    = f.file_field :avatar

  %div{class:"field"}
    = f.label :nickname
    %br
    = f.text_field :nickname

  %div{class:"field"}
    = f.label :description
    %br
    = f.text_field :description

  %div{class:"field"}
    = f.label :date_added
    %br
    = f.date_select(:date_added, :disabled => true)
  </div>

  %div{class:"actions"}
    = submit_tag 'Save'

app/views/contestants/edit.html.haml
%h1 Editing contestant

=render 'form'

=link_to 'Details', @contestant
=link_to 'Back', contestants_path

app/views/contestants/index.html.haml
%h1 Listing contestants

%table{class: "contestants-table"}
  %tbody
  - @contestants.each do |c|
    %tr
      %td
        =link_to image_tag(c.avatar.url, :class=>'profile-image-small'),edit_contestant_path(c)
      %td=c.first_name
      %td= "" + c.nickname + ""
      %td=c.last_name
      %td=c.description
      %td=c.date_added
      %td=link_to 'Details', contestant_path(c)
      %td=link_to 'Edit', edit_contestant_path(c)
      %td=link_to 'Delete', c, method: :delete, data: {confirm: 'Are you sure?' }

%br
%div= link_to 'New Contestant',   new_contestant_path

app/views/contestants/new.html.haml
%h1 New contestant

= render 'form'

= link_to 'Back to contestants', contestants_path

app/views/contestants/show.html.haml
%h2 #{@contestant.first_name} "#{@contestant.nickname}" #{@contestant.last_name}

%p{id:"notice"}
  = image_tag @contestant.avatar.url, :class => "profile-image-large"

%p
  %strong Description:
  = @contestant.description

%p
  %strong Date added:
  %span{class:"date-added"}=@contestant.date_added.strftime('%a %d %b, %Y')

%div= link_to 'Edit', edit_contestant_path(@contestant)
%div= link_to 'Back', contestants_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
  %title Brew-Ha-Ha
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

  %body
    = yield